app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
    Route::resource('cooperativas', 'CooperativaController');
    Route::resource('solicitudes', 'SolicitudController');
    Route::resource('tipoprestamo', 'TipoPrestamoController');
    Route::resource('credito', 'CreditoController');
    Route::resource('mineral', 'TipoMineralController');
    Route::resource('desembolso', 'DesembolsoController');
    Route::resource('amortizacion', 'AmortizacionController');
    Route::resource('reporte', 'ReporteController');
    Route::post('aprobarsolicitud', 'SolicitudController@aprobarsolicitud');
    Route::get('/test', 'CreditoController@testPlanCredito');
    // Plan de creditos
    Route::get('/plan', 'CreditoController@editPlanCredito');
    Route::post('/plan', 'CreditoController@updatePlanCredito');
    Route::get('/test2', 'CreditoController@testPlanCredito2');
});

Route::get('API/{solicitud}', function (App\Solicitud $solicitud){
    return $solicitud;
})->middleware('throttle:3');

app/Cooperativa.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Collective\Html\Eloquent\FormAccessible;

class Cooperativa extends Model
{
    use FormAccessible;
    //
    protected $fillable = ['nombre', 'codigo', 'nro_registro', 'derecho_consesionario', 'federacion_afiliada',
        'ci_representante_legal', 'nombre_representante_legal', 'cantidad_socios', 'fecha_formacion', 'fecha_resolucion', 'direccion', 'departamento_id', 'provincia_id',
        'municipio_id', 'localidad_id', 'telefono', 'fax', 'casilla_postal', 'email', 'web', 'mineral_id', 'latitude', 'longitude', 'personeria_juridica', 'coordinadas_utm', 'produccion_anual'];

    public function getFechaFormacionAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y');
    }

    public function formFechaFormacionAttribute($value)
    {
        return Carbon::parse($value)->format('m-d-Y');
    }

    public function getFechaResolucionAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y');
    }

    public function formFechaResolucionAttribute($value)
    {
        return Carbon::parse($value)->format('m-d-Y');
    }
}

app/Http/Controllers/CooperativaController.php
<?php

namespace App\Http\Controllers;

use App\Cooperativa;
use App\TipoMineral;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
//use Validator, Input, Redirect;
use App\Http\Requests;

class CooperativaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cooperativas = Cooperativa::orderBy('created_at', 'asc')->get();

        return view('cooperativa.list', [
            'cooperativas' => $cooperativas
        ]);
        //return view('cooperativa.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $minerales = TipoMineral::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        return view('cooperativa.create',['minerales' => $minerales]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|max:255',
            'nro_registro' => 'unique:cooperativas|required',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withInput()
                ->withErrors($validator);
        }

        $cooperativa = new Cooperativa();
        $input = $request->all();
        $cooperativa->fill($input);
        $cooperativa->save();

        return redirect('/cooperativas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cooperativa = Cooperativa::findOrFail($id);
        $mineral = TipoMineral::find($cooperativa->mineral_id);
        $cooperativa->mineral= empty($mineral->nombre)? '':$mineral->nombre;
        return view('cooperativa.show')->withCooperativa($cooperativa);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $cooperativa = Cooperativa::findOrFail($id);
        $minerales = TipoMineral::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        return view('cooperativa.edit',['minerales' => $minerales])->withCooperativa($cooperativa);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $cooperativa = Cooperativa::findOrFail($id);
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|max:255',
            'nro_registro' => 'required',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withInput()
                ->withErrors($validator);
        }
        $input = $request->all();
        $cooperativa->fill($input);
        $cooperativa->save();


        return redirect('/cooperativas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/cooperativa/create.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Cooperativas
@endsection
@section('htmlheader_title')
	Crear
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Nueva Cooperativa</h3>
              <div class="box-tools pull-right">
                            <a href="{{url('cooperativas')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-th-large'></i> Lista</a>

                            </div>
            </div><!-- /.box-header -->
            <div class="box-body">
<!-- New Task Form -->
        @include('layouts.partials.errors')
        <form action="{{ url('cooperativas') }}" method="POST" class="form-horizontal">
            {!! csrf_field() !!}

            <!-- Nombre -->
            <div class="form-group">
                <label for="nombre" class="col-sm-3 control-label">* Nombre o razón social de la cooperativa solicitante</label>

                <div class="col-sm-6">
                    <input type="text" name="nombre" id="coop-nombre" class="form-control" value="{{ old('nombre') }}">
                </div>
            </div>
            <!-- Personeria juridica -->
                        <div class="form-group">
                            <label for="personeria_juridica" class="col-sm-3 control-label">Personeria Juridica</label>

                            <div class="col-sm-6">
                                <input type="text" name="personeria_juridica" id="personeria_juridica" class="form-control" value="{{ old('personeria_juridica') }}">
                            </div>
                        </div>
            <!-- Codigo -->
            <div class="form-group">
                <label for="codigo" class="col-sm-3 control-label">Codigo</label>

                <div class="col-sm-6">
                    <input type="text" name="codigo" id="codigo" class="form-control" value="{{ old('codigo') }}">
                </div>
            </div>
            <!-- Nro de Registro -->
            <div class="form-group">
                <label for="nro_registro" class="col-sm-3 control-label">NRO. DE REGISTRO</label>

                <div class="col-sm-6">
                    <input type="text" name="nro_registro" id="coop-registro" class="form-control">
                </div>
            </div>
            <!-- Derecho consesionario -->
            <div class="form-group">
                <label for="derecho_consesionario" class="col-sm-3 control-label">DERECHO CONSESIONARIO</label>

                <div class="col-sm-6">
                    <input type="text" name="derecho_consesionario" id="coop-derecho_c" class="form-control">
                </div>
            </div>
            <!-- Federacion -->
            <div class="form-group">
                <label for="federacion_afiliada" class="col-sm-3 control-label">Federacion Afiliada</label>

                <div class="col-sm-6">
                    <input type="text" name="federacion_afiliada" id="coop-federacion" class="form-control">
                </div>
            </div>
            <!-- CI -->
            <div class="form-group">
                <label for="ci_representante_legal" class="col-sm-3 control-label">C.I. Representante Legal</label>

                <div class="col-sm-6">
                    <input type="text" name="ci_representante_legal" id="coop-ci" class="form-control">
                </div>
            </div>
            <!-- Nombre RL -->
            <div class="form-group">
                <label for="nombre_representante_legal" class="col-sm-3 control-label">Nombre Representante Legal</label>

                <div class="col-sm-6">
                    <input type="text" name="nombre_representante_legal" id="coop-nombre_rl" class="form-control">
                </div>
            </div>
            <!-- Fecha de Formacion -->
            <div class="form-group">
                <label for="fecha_formacion" class="col-sm-3 control-label">Fecha Formacion</label>

                <div class="col-sm-6">
                    <input type="date" name="fecha_formacion" id="coop-fecha_forma" class="form-control">
                </div>
            </div>
            <!-- Fecha Resolucion -->
            <div class="form-group">
                <label for="fecha_resolucion" class="col-sm-3 control-label">Fecha Resolucion</label>

                <div class="col-sm-6">
                    <input type="date" name="fecha_resolucion" id="coop-fecha_resol" class="form-control">
                </div>
            </div>
            <!-- Direccion -->
            <div class="form-group">
                <label for="direccion" class="col-sm-3 control-label">Direccion</label>

                <div class="col-sm-6">
                    <input type="text" name="direccion" id="coop-direccion" class="form-control">
                </div>
            </div>
            <div class="form-group">
                            <label for="coordinadas_utm" class="col-sm-3 control-label">Coor. UTM</label>

                            <div class="col-sm-6">
                                <input type="text" name="coordinadas_utm" id="coordinadas_utm" class="form-control">
                            </div>
                        </div>
            <!-- Telefono -->
            <div class="form-group">
                <label for="telefono" class="col-sm-3 control-label">Telefono</label>

                <div class="col-sm-6">
                    <input type="text" name="telefono" id="coop-telefono" class="form-control">
                </div>
            </div>
            <!-- Fax -->
            <div class="form-group">
                <label for="fax" class="col-sm-3 control-label">Fax</label>

                <div class="col-sm-6">
                    <input type="text" name="fax" id="coop-fax" class="form-control">
                </div>
            </div>

            <!-- eMail -->
            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Email</label>

                <div class="col-sm-6">
                    <input type="email" name="email" id="coop-email" class="form-control">
                </div>
            </div>

            <!-- Website -->
            <div class="form-group">
                <label for="web" class="col-sm-3 control-label">Website</label>

                <div class="col-sm-6">
                    <input type="text" name="web" id="coop-web" class="form-control">
                </div>
            </div>
            <div class="form-group">
                {!! Form::label('mineral_id', 'Mineral de Produccion:', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::select('mineral_id', $minerales, ['class' => 'form-control']) !!}
                    </div>
            </div>
            <div class="form-group">
                {!! Form::label('produccion_anual', 'Produccion Anual:', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-6">
                    {!! Form::text('produccion_anual', '', ['class' => 'form-control']) !!}
                    </div>
            </div>
            <!-- Add Button -->
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Añadir nuevo
                    </button>
                </div>
            </div>
        </form>

            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
{{--@push('pagescripts')--}}
{{--<script>--}}
{{--$(document).ready(function() {--}}
    {{--$('#example').DataTable();--}}
{{--} );--}}
{{--</script>--}}
{{--@endpush--}}

resources/views/cooperativa/edit.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Cooperativas
@endsection
@section('htmlheader_title')
	Editar
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Editar Cooperativa</h3>
              <div class="box-tools pull-right">
                            <a href="{{url('cooperativas')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-th-large'></i> Lista</a>

                            </div>
            </div><!-- /.box-header -->
            <div class="box-body">
<!-- New Task Form -->
        @include('layouts.partials.errors')
        {!! Form::model($cooperativa, array('route' => array('cooperativas.update', $cooperativa->id), 'method' => 'put')) !!}


        <div class="form-group">
            {!! Form::label('nombre', 'NOMBRE O RAZÓN SOCIAL DE LA COOPERATIVA SOLICITANTE:', ['class' => 'control-label']) !!}
            {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('personeria_juridica', 'Personeria Juridica:', ['class' => 'control-label']) !!}
            {!! Form::text('personeria_juridica', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('codigo', 'Codigo:', ['class' => 'control-label']) !!}
            {!! Form::text('codigo', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('nro_registro', 'Nro Registro:', ['class' => 'control-label']) !!}
            {!! Form::text('nro_registro', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('derecho_consesionario', 'Derecho Consesionario:', ['class' => 'control-label']) !!}
            {!! Form::text('derecho_consesionario', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('federacion_afiliada', 'Federacion Afiliada:', ['class' => 'control-label']) !!}
            {!! Form::text('federacion_afiliada', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('ci_representante_legal', 'C.I. Representante legal:', ['class' => 'control-label']) !!}
            {!! Form::text('ci_representante_legal', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('nombre_representante_legal', 'Nombre Representante legal:', ['class' => 'control-label']) !!}
            {!! Form::text('nombre_representante_legal', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('fecha_formacion', 'Fecha Formacion:', ['class' => 'control-label']) !!}
            {!! Form::input('date', 'fecha_formacion', \Carbon\Carbon::now(), ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('fecha_resolucion', 'Fecha Resolucion:', ['class' => 'control-label']) !!}
            {!! Form::input('date', 'fecha_resolucion', \Carbon\Carbon::now(), ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('direccion', 'Direccion:', ['class' => 'control-label']) !!}
            {!! Form::text('direccion', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('coordinadas_utm', 'Coor. UTM:', ['class' => 'control-label']) !!}
            {!! Form::text('coordinadas_utm', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('telefono', 'Telefono:', ['class' => 'control-label']) !!}
            {!! Form::text('telefono', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('fax', 'Fax:', ['class' => 'control-label']) !!}
            {!! Form::text('fax', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('web', 'Website:', ['class' => 'control-label']) !!}
            {!! Form::text('web', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('mineral_id', 'Mineral de Produccion:', ['class' => 'control-label']) !!}
            {!! Form::select('mineral_id', $minerales, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('produccion_anual', 'Produccion Anual:', ['class' => 'control-label']) !!}
            {!! Form::text('produccion_anual', null, ['class' => 'form-control']) !!}
        </div>

        {!! Form::submit('Actualizar registro', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}

            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
{{--@push('pagescripts')--}}
{{--<script>--}}
{{--$(document).ready(function() {--}}
    {{--$('#example').DataTable();--}}
{{--} );--}}
{{--</script>--}}
{{--@endpush--}}

resources/views/cooperativa/list.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Cooperativas
@endsection
@section('htmlheader_title')
	Lista
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Cooperativas</h3>
              <div class="box-tools pull-right">
              <a href="{{url('cooperativas/create')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-plus'></i> Nueva</a>
                {{--<div class="has-feedback">--}}
                  {{--<input type="text" class="form-control input-sm" placeholder="Busqueda...">--}}
                  {{--<span class="glyphicon glyphicon-search form-control-feedback"></span>--}}
                {{--</div>--}}
              </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
            <div class="box-body">
<table id="cooperativa_list" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Acciones</th>
                <th>Nombre</th>
                <th>Codigo</th>
                <th>Nro. Registro</th>
                <th>CI representante</th>
                <th>Representante</th>
                <th>Fecha Formacion</th>
            </tr>
        </thead>
        {{--<tfoot>--}}
            {{--<tr>--}}
                            {{--<th>Acciones</th>--}}
                            {{--<th>Nombre</th>--}}
                            {{--<th>Codigo</th>--}}
                            {{--<th>Nro. Registro</th>--}}
                            {{--<th>CI representante</th>--}}
                            {{--<th>Nro. Socios</th>--}}
                            {{--<th>Fecha Formacion</th>--}}
                        {{--</tr>--}}
        {{--</tfoot>--}}
        <tbody>
        @foreach ($cooperativas as $cooperativa)
            <tr>
                <td>
                <div class="btn-group">
                <a href="{{route('cooperativas.show', $cooperativa->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                <a href="{{route('cooperativas.edit', $cooperativa->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                {{--<a href="{{route('cooperativas.show', $cooperativa->id)}}" class="btn btn-warning btn-xs"><i class='fa fa-user'></i> </a>--}}
                                {{--<form action="{{ url('cooperativas/'.$cooperativa->id) }}" method="POST">--}}
                                {{--{!! csrf_field() !!}--}}
                                    {{--{!! method_field('DELETE') !!}--}}

                                    {{--<button type="submit" class="btn btn-danger btn-box-tool">--}}
                                        {{--<i class="fa fa-trash"></i>--}}
                                    {{--</button>--}}
                                {{--</form>--}}
                </div>

                </td>
                <td>{{ $cooperativa->nombre }}</td>
                <td>{{ $cooperativa->codigo }}</td>
                <td>{{ $cooperativa->nro_registro }}</td>
                <td>{{ $cooperativa->ci_representante_legal }}</td>
                <td>{{ $cooperativa->nombre_representante_legal }}</td>
                <td>{{ $cooperativa->fecha_formacion }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
@push('pagescripts')
<script>
$(document).ready(function() {
    $('#cooperativa_list').DataTable();
} );
</script>
@endpush

resources/views/cooperativa/show.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Cooperativas
@endsection
@section('htmlheader_title')
	Detalle
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title"><b>Cooperativa</b> {{$cooperativa->nombre}}</h3>
              <div class="box-tools pull-right">
                    <a href="{{route('cooperativas.edit', $cooperativa->id)}}" class="btn btn-sm btn-primary btn-flat pull-left"><i class='fa fa-edit'></i> </a>
                    <a href="{{url('cooperativas')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-th-large'></i> Lista</a>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <h4><b>Nombre o razón social de la cooperativa solicitante:</b> {{$cooperativa->nombre}}</h4>
                <h4><b>Personeria Juridica:</b> {{$cooperativa->personeria_juridica}}</h4>
                <h4><b>Codigo:</b> {{$cooperativa->codigo}}</h4>
                <h4><b>Nro. de Registro:</b> {{$cooperativa->nro_registro}}</h4>
                <h4><b>Derecho Consesionario:</b> {{$cooperativa->derecho_consesionario}}</h4>
                <h4><b>Federacion Afiliada:</b> {{$cooperativa->federacion_afiliada}}</h4>
                <h4><b>C.I. Representante Legal:</b> {{$cooperativa->ci_representante_legal}}</h4>
                <h4><b>Nombre Representante Legal:</b> {{$cooperativa->nombre_representante_legal}}</h4>
                <h4><b>Fecha Formacion:</b> {{$cooperativa->fecha_formacion}}</h4>
                <h4><b>Fecha Resolucion:</b> {{$cooperativa->fecha_resolucion}}</h4>
                <h4><b>Direccion:</b> {{$cooperativa->direccion}}</h4>
                <h4><b>Coor. UTM:</b> {{$cooperativa->coordinadas_utm}}</h4>
                <h4><b>Telefono:</b> {{$cooperativa->telefono}}</h4>
                <h4><b>Fax:</b> {{$cooperativa->fax}}</h4>
                <h4><b>Email:</b> {{$cooperativa->email}}</h4>
                <h4><b>Website:</b> {{$cooperativa->web}}</h4>
                <h4><b>Mineral de Producción:</b> {{$cooperativa->mineral}}</h4>
                <h4><b>Producción Anual:</b> {{$cooperativa->produccion_anual}}</h4>
                <div class="col-md-6 pull-right">
                    {!! Form::open([
                        'method' => 'DELETE',
                        'route' => ['cooperativas.destroy', $cooperativa->id]
                    ]) !!}
                        {!! Form::submit("Eliminar", ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                </div>
            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
{{--@push('pagescripts')--}}
{{--<script>--}}
{{--$(document).ready(function() {--}}
    {{--$('#example').DataTable();--}}
{{--} );--}}
{{--</script>--}}
{{--@endpush--}}