app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
    Route::resource('cooperativas', 'CooperativaController');
    Route::resource('solicitudes', 'SolicitudController');
    Route::resource('tipoprestamo', 'TipoPrestamoController');
    Route::resource('credito', 'CreditoController');
    Route::resource('mineral', 'TipoMineralController');
    Route::resource('desembolso', 'DesembolsoController');
    Route::resource('amortizacion', 'AmortizacionController');
    Route::resource('reporte', 'ReporteController');
    Route::post('aprobarsolicitud', 'SolicitudController@aprobarsolicitud');
    Route::get('/test', 'CreditoController@testPlanCredito');
    // Plan de creditos
    Route::get('/plan', 'CreditoController@editPlanCredito');
    Route::post('/plan', 'CreditoController@updatePlanCredito');
    Route::get('/test2', 'CreditoController@testPlanCredito2');
});

Route::get('API/{solicitud}', function (App\Solicitud $solicitud){
    return $solicitud;
})->middleware('throttle:3');

app/Credito.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DateTime;

class Credito extends Model
{
    //
    protected $fillable = array('solicitud_id', 'cooperativa_id', 'codigo_prestamo',
        'estado_prestamo','fecha_desembolso', 'fecha_pago','moneda','plazo','tiempo_gracia',
        'importe_credito','total_mes','tasa','interes','cuota_capital','saldo_capital',
        'suma_total_pagado','ultima_amortizacion');
    /**
     * Get the comments for the blog post.
     */
    public function plan()
    {
        return $this->hasMany('App\PlanCredito');
    }
    // TODO REMOVE DEPRECATED
    public function movimientos()
    {
        return $this->hasMany('App\MovimientoCredito');
    }
    public function movimientosD()
    {
        return $this->hasMany('App\MovimientoCredito');
    }
    public function movimientosA()
    {
        return $this->hasMany('App\MovimientoCredito');
    }

    public function amortizacion()
    {
        return $this->hasMany('App\Amortizacion');
    }
    public function desembolso()
    {
        return $this->hasMany('App\Desembolso');
    }
    public static function createNewPlanCredito($saldo_capital, $plazo, $gracia, $interesAnual, $fecha_ini, $diaPago, $i = 1)
    {
        // Generate Interes
        // Mensual: anual/mesesAño/porcentaje
        $interes_mensual = $interesAnual/12/100;
        // Diario: Mensual/30Dias
        $interesDiario = $interes_mensual/30;

        // Generate Dates TODO Agregar DiaPago
        $start = new DateTime($fecha_ini);
        $year = $start->format('Y');
        $month = $start->format('m');
        $day = $start->format('d');
        $finishDate = new DateTime($fecha_ini);
        $finishDate->setDate($year, $month + $plazo,$diaPago);
        //return $start->format('Y-m-d');
        //return $finishDate->format('Y-m-d');

        // Main loop
        $tempOldDate = new DateTime($fecha_ini);
        $mainPC = [];
        $cuotaCapitalMes = $saldo_capital / ($plazo - $gracia);
        $saldoCapital = $saldo_capital;
        for(; $i<=$plazo; $i++){
            $mainPC[$i]['cuota'] = $i;
            $tempNewDate = new DateTime();
            $tempNewDate->setDate($year,$month+$i,$diaPago);
            $mainPC[$i]['fechaInicio'] = $tempOldDate->format('Y-m-d');
            $mainPC[$i]['fechaPago'] = $tempNewDate->format('Y-m-d');
            $tempDateDiff = date_diff($tempOldDate,$tempNewDate, '%d')->days;
            if($i<=$gracia){
                $mainPC[$i]['capitalAmortizar'] = 0;
                $mainPC[$i]['periodoGracia'] = 0;
            }
            else {
                $mainPC[$i]['capitalAmortizar'] = round($cuotaCapitalMes,2);
                $mainPC[$i]['periodoGracia'] = 1;
            }
            $mainPC[$i]['interesSaldos'] = round($saldoCapital*$interesDiario*$tempDateDiff, 2);
            $saldoCapital -= $mainPC[$i]['capitalAmortizar'];
            $mainPC[$i]['cuotaTotalMes'] = round($mainPC[$i]['capitalAmortizar'] + $mainPC[$i]['interesSaldos'], 2);
            $mainPC[$i]['saldoCapital'] = round($saldoCapital, 2);
            $tempOldDate = new DateTime();
            $tempOldDate->setDate($year,$month+$i,$diaPago);
        }
        return $mainPC;
    }

    public function terminarCredito () {
        $sum = 0;
        $amortizacion = $this->amortizacion();
        foreach ($amortizacion as $row) {
            $sum = $sum+ $row['importe'];
        }
        if ($sum == $this->importe_credito){
            return "credito completado";
        }
        else {
            return "Credito por completar";
        }
    }
}

app/Http/Controllers/CreditoController.php
<?php

namespace App\Http\Controllers;

use App\Credito;
use App\Solicitud;
use App\Cooperativa;
use App\TipoPrestamo;
use App\ResolucionSolicitud;
use App\PlanCredito;
use App\MovimientoCredito;
use App\Amortizacion;
use App\Desembolso;

use DateInterval;
use DatePeriod;
use DateTime;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Http\Request;

use App\Http\Requests;

class CreditoController extends Controller
{

    /**
     * List of to-dos
     * Remap Desembolsos
     * Create new views for amortizaciones
     * Create controller for amortizaciones
     * End a credit
     * Update mainscreen with realdata values
     * Make a report
     * Include delete action on controller
     * Include delete action on view
     *
     */
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cooperativas = Cooperativa::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
//        $tipo_prestamos = TipoPrestamo::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        $creditos = Credito::orderBy('created_at', 'asc')->get();

        return view('credito.list', [
            'creditos' => $creditos,
//            'tipo_prestamos' => $tipo_prestamos,
            'cooperativas' => $cooperativas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'solicitud_id' => 'required',
//            'codigo_prestamo' => 'unique:creditos|required',
            'codigo_prestamo' => 'required',
            'fecha_aprobacion' => 'required',
            'fecha_desembolso' => 'required',
            'fecha_pago' => 'required',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withInput()
                ->withErrors($validator);
        }

        $id = $request->solicitud_id;
        $solicitud = Solicitud::findOrFail($id);

        // ESTADOS.- 0. pendiente, 1. aprobada, 2.rechazada
        if ($solicitud->estado >= 1) {
            return Redirect::back()
                ->withInput()
                ->withErrors(array("La solicitud ya fue aprobada, contacte al administrador del sistema."));
//            return "Error. La solicitud ya fue aprobada, contacte al administrador del sistema.";
        }


        $tipo_prestamo = TipoPrestamo::findOrFail($solicitud->tipo_credito_id);
        $cooperativa = Cooperativa::findOrFail($solicitud->cooperativa_id);


        $saldo_capital = $solicitud->importe_solicitado;
        $plazo = $tipo_prestamo->tiempo_maximo_pago;
        $gracia = $tipo_prestamo->tiempo_de_gracia;
        $interes_anual = $tipo_prestamo->interes;
        //la fecha de inicio comienza al primer desembolso
        $fecha_ini = $request->fecha_desembolso;
        $fecha_pago = $request->fecha_pago;

        $detalle_plan = Credito::createNewPlanCredito($saldo_capital, $plazo, $gracia, $interes_anual, $fecha_ini, $fecha_pago);

        //  Old Plan TODO Remove this
        //$detalle_plan = $this->createPlanCredito($saldo_capital, $plazo, $gracia, $interes_anual, $fecha_ini);

        $resolucion = new ResolucionSolicitud();
        $resolucion->fill(array('solicitud_id' => $solicitud->id, 'estado' => 1,
            "fecha_resolucion" => $request->fecha_aprobacion, 'monto_aprobado' => $solicitud->importe_solicitado));
        // Start Debugging here
        //return $resolucion;
        $resolucion->save();
        $solicitud->estado = 1;
        $solicitud->save();

//      Creando el nuevo credito

        $credito = new Credito();
        $data = ['solicitud_id' => $solicitud->id,
            'cooperativa_id' => $solicitud->cooperativa_id,
            'codigo_prestamo' => $request->codigo_prestamo,
            //Estado del Prestamo: 0. pendiente, 1. Finalizado, 2. Otros
            'estado_prestamo' => 0,
            'fecha_desembolso' => $fecha_ini,
            'fecha_pago' => $request->fecha_pago,
            'moneda' => 'Bolivianos',
            'plazo' => $plazo,
            'tiempo_gracia' => $gracia,
            'importe_credito' => $saldo_capital,
            'interes' => $interes_anual,
            'saldo_capital' => $saldo_capital,
            'suma_total_pagado' => 0,

        ];
        $credito->fill($data);
        $credito->save();

//        return $detalle_plan;
        // todo llenando plan de creditos

        foreach ($detalle_plan as $row) {
            $plan_row = new PlanCredito();
            $plan_row->credito_id = $credito->id;
            $plan_row->periodo_gracia = $row['periodoGracia'];
            $plan_row->fecha_pago = $row['fechaPago'];
            $plan_row->cuota_capital = $row['capitalAmortizar'];
            $plan_row->cuota_interes = $row['interesSaldos'];
            $plan_row->total_cuota = $row['cuotaTotalMes'];
            $plan_row->saldo_capital = $row['saldoCapital'];
            $plan_row->save();
//            return $plan_row;
        }

        return redirect("/credito/" . $credito->id);
//        return "Solicitud Correctamente Aprobada";
//        $value = new Solicitud();
//        $input = $request->all();
//        $value->fill($input);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $credito = Credito::findOrFail($id);
        $plan = $credito->plan;
        // todo Update according
        //$desembolso = $credito->movimientos()->where('tipo', 0)->get();
        //$amortizacion = $credito->movimientos()->where('tipo', 1)->get();
        $desembolso = $credito->desembolso;
        $amortizacion = $credito->amortizacion;
        $cooperativa = Cooperativa::findOrFail($credito->cooperativa_id);
        $solicitud = Solicitud::findOrFail($credito->solicitud_id);
        $sum = array();
//return $solicitud;
//        Sum amortizaciones
        $sumAmortizacion = 0;
        if (!empty($amortizacion)) {
            foreach ($amortizacion as $row) {
                $sumAmortizacion = $sumAmortizacion + $row['importe'];
            }
        }
        $sum['amortizacion'] = $sumAmortizacion;

//        Sum desembolsos
        $sumDesembolsos = 0;
        if (!empty($desembolso)) {
            foreach ($desembolso as $row) {
                $sumDesembolsos = $sumDesembolsos + $row['importe'];
            }
        }
        $sum['desembolso'] = $sumDesembolsos;

//        return $credito;
//        return $plan;


//        $saldo_capital=$solicitud->importe_solicitado;
//        $plazo=$tipo_prestamo->tiempo_maximo_pago;
//        $gracia=$tipo_prestamo->tiempo_de_gracia;
//        $interes_anual=$tipo_prestamo->interes;
//        $fecha_ini=$solicitud->fecha_solicitud;

        return view('credito.show',
            ['cooperativa' => $cooperativa,
                'solicitud' => $solicitud,
                'amortizacion' => $amortizacion,
                'desembolso' => $desembolso,
                'sum' => $sum,
                'detalle_plan' => $plan])->withCredito($credito);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function editPlanCredito(){
        $data = $this->testPlanCredito();
//        return $data;
        return view('credito.plan', ['data' => $data]);
    }

    public function updatePlanCredito(){
        $data = $this->testPlanCredito();
//        return $data;
        return view('credito.plan', ['data' => $data]);
    }

    public function testPlanCredito2(){
        $data = $this->testPlanCredito();
//        return $data;
        return view('credito.plan', ['data' => $data]);
    }


    public function testPlanCredito() {
        // Pruebas Plan
        $monto_prestamo = 376380;
        $interes_anual = 6;
        $plazo = 36;
        $gracia = 3;
        $fecha_ini = "2016-03-23";
        // Nueva Variable: Dia Pago
        $diaPago = 29;
        $PC1 = Credito::createNewPlanCredito($monto_prestamo, $plazo, $gracia, $interes_anual, $fecha_ini, $diaPago,1);

        $monto_prestamo = 418200;
        $interes_anual = 6;
        $plazo = 31;
        $gracia = 0;
        $fecha_ini = "2016-09-08";
        // Nueva Variable: Dia Pago
        $diaPago = 29;
        $PC2 = Credito::createNewPlanCredito($monto_prestamo, $plazo, $gracia, $interes_anual, $fecha_ini, $diaPago);
        return $PC2;
        //return $PC1;
    }

    public function testPlanCreditoOriginal()
    {
        // Pruebas Plan
        $monto_prestamo = 800000;
        $interes_anual = 6;
        $plazo = 36;
        $gracia = 3;
        $fecha_ini = "2015-12-29";
        // Nueva Variable: Dia Pago
        $diaPago = 29;
        $PC1 = Credito::createNewPlanCredito($monto_prestamo, $plazo, $gracia, $interes_anual, $fecha_ini, $diaPago);
        return $PC1;

        // if going to add to movimientos

resources/views/credito/create.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Solicitud
@endsection
@section('htmlheader_title')
	Crear
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Nueva Solicitud</h3>
              <div class="box-tools pull-right">
                            <a href="{{url('solicitudes')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-th-large'></i> Lista</a>

                            </div>
            </div><!-- /.box-header -->
            <div class="box-body">
<!-- New Task Form -->
        @include('layouts.partials.errors')
                {!! Form::open(array('url' => 'solicitudes')) !!}
                {!! csrf_field() !!}

            <!-- Nombre -->
                <div class="form-group">
                    {!! Form::label('cooperativa_id', 'Cooperativa:', ['class' => 'control-label']) !!}

                    {!! Form::select('cooperativa_id', $cooperativas) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('tipo_credito_id', 'Tipo Creditos:', ['class' => 'control-label']) !!}
                    {!! Form::select('tipo_credito_id', $tipo_prestamos) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('nro_solicitud', 'Nro. Solicitud:', ['class' => 'control-label']) !!}
                    {!! Form::text('nro_solicitud', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('nombre_proyecto', 'Nombre del Proyecto:', ['class' => 'control-label']) !!}
                    {!! Form::text('nombre_proyecto', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                            {!! Form::label('fecha_solicitud', 'Fecha Solicitud:', ['class' => 'control-label']) !!}
                            {!! Form::input('date', 'fecha_solicitud', date('d-m-Y'), ['class' => 'form-control']) !!}
                        </div>
                <div class="form-group">
                    {!! Form::label('importe_solicitado', 'Importe Solicitado:', ['class' => 'control-label']) !!}
                    {!! Form::text('importe_solicitado', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('importe_propio', 'Importe Propio:', ['class' => 'control-label']) !!}
                    {!! Form::text('importe_propio', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('importe_total', 'Importe Total:', ['class' => 'control-label']) !!}
                    {!! Form::text('importe_total', null, ['class' => 'form-control']) !!}
                </div>
                {{--<div class="form-group">--}}
                    {{--{!! Form::label('adjunto', 'Archivo Adjunto:', ['class' => 'control-label']) !!}--}}
                    {{--{!! Form::file('adjunto', null, ['class' => 'form-control']) !!}--}}
                {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--{!! Form::label('requisitos', 'Requisitos:', ['class' => 'control-label']) !!}--}}
                    {{--{!! Form::text('requisitos', null, ['class' => 'form-control']) !!}--}}
                {{--</div>--}}

                {{--array('cooperativa_id', 'tipo_credito_id', 'nro_solicitud', 'nombre_proyecto', 'fecha_solicitud',--}}
                {{--'importe_solicitado','importe_propio', 'importe_total','estado');--}}
            <!-- Add Button -->
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Añadir nuevo
                    </button>
                </div>
            </div>

        {!! Form::close() !!}

            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
{{--@push('pagescripts')--}}
{{--<script>--}}
{{--$(document).ready(function() {--}}
    {{--$('#example').DataTable();--}}
{{--} );--}}
{{--</script>--}}
{{--@endpush--}}

resources/views/credito/list.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Creditos
@endsection
@section('htmlheader_title')
	Lista
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
        <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Todos los creditos</a></li>
                      <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">En curso</a></li>
                      <li><a href="#tab_3" data-toggle="tab">Finalizados</a></li>
                      {{--<li class="pull-right"><a href="{{url('solicitudes/list')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-plus'></i> Nueva Solicitud</a></li>--}}
                    </ul>
                    <div class="tab-content">
                      <div class="tab-pane active" id="tab_1">
                        <div class="box-body">
                        <table id="credito_list" class="display" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Acciones</th>
                                        <th>Estado</th>
                                        <th>Cooperativa</th>
                                        <th>Codigo</th>
                                        <th>Saldo Capital</th>
                                        <th>Plazo</th>
                                        <th>Tiempo de Gracia</th>
                                        <th>Interes</th>
                                    </tr>
                                </thead>

                                <tbody>
                                @foreach ($creditos as $credito)
                                    <tr>
                                        <td>
                                        <div class="btn-group">
                                        <a href="{{route('credito.show', $credito->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                                        <a href="{{route('credito.edit', $credito->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                                        </div>

                                        </td>
                                        <td>{{ $credito->estado==0? "En curso":"Completado"  }}</td>
                                        <td>{{ $cooperativas[$credito->cooperativa_id] }}</td>
                                        <td>{{ $credito->codigo_prestamo }}</td>
                                        <td>{{ $credito->saldo_capital}} BOB</td>
                                        <td>{{ $credito->plazo }} meses</td>
                                        <td>{{ $credito->tiempo_gracia }} meses</td>
                                        <td>{{ $credito->interes }} %</td>

                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                                    </div>
                      </div>
                      <!-- /.tab-pane -->
                      <div class="tab-pane" id="tab_2">
                        <div class="box-body">
                                        <table id="credito_b_list" class="display" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>
                                                <th>Acciones</th>
                                                <th>Estado</th>
                                                <th>Cooperativa</th>
                                                <th>Codigo</th>
                                                <th>Saldo Capital</th>
                                                <th>Plazo</th>
                                                <th>Tiempo de Gracia</th>
                                                <th>Interes</th>
                                            </tr>
                                            </thead>

                                            <tbody>
                                            @foreach ($creditos as $credito)
                                                @if($credito->estado == 0)
                                                <tr>
                                                    <td>
                                                        <div class="btn-group">
                                                            <a href="{{route('credito.show', $credito->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                                                            <a href="{{route('credito.edit', $credito->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                                                        </div>

                                                    </td>
                                                    <td>{{ $credito->estado==0? "En curso":"Completado"  }}</td>
                                                    <td>{{ $cooperativas[$credito->cooperativa_id] }}</td>
                                                    <td>{{ $credito->codigo_prestamo }}</td>
                                                    <td>{{ $credito->saldo_capital}} BOB</td>
                                                    <td>{{ $credito->plazo }} meses</td>
                                                    <td>{{ $credito->tiempo_gracia }} meses</td>
                                                    <td>{{ $credito->interes }} %</td>

                                                </tr>
                                                @endif
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                      </div>
                      <!-- /.tab-pane -->
                      <div class="tab-pane" id="tab_3">
                        <div class="box-body">
                                        <table id="credito_a_list" class="display" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>
                                                <th>Acciones</th>
                                                <th>Estado</th>
                                                <th>Cooperativa</th>
                                                <th>Codigo</th>
                                                <th>Saldo Capital</th>
                                                <th>Plazo</th>
                                                <th>Tiempo de Gracia</th>
                                                <th>Interes</th>
                                            </tr>
                                            </thead>

                                            <tbody>
                                            @foreach ($creditos as $credito)
                                                @if($credito->estado==1)
                                                <tr>
                                                    <td>
                                                        <div class="btn-group">
                                                            <a href="{{route('credito.show', $credito->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                                                            <a href="{{route('credito.edit', $credito->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                                                        </div>

                                                    </td>
                                                    <td>{{ $credito->estado==0? "En curso":"Completado"  }}</td>
                                                    <td>{{ $cooperativas[$credito->cooperativa_id] }}</td>
                                                    <td>{{ $credito->codigo_prestamo }}</td>
                                                    <td>{{ $credito->saldo_capital}} BOB</td>
                                                    <td>{{ $credito->plazo }} meses</td>
                                                    <td>{{ $credito->tiempo_gracia }} meses</td>
                                                    <td>{{ $credito->interes }} %</td>

                                                </tr>
                                                @endif
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                      </div>
                      <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                  </div>

      </div>

@endsection
@push('pagescripts')
<script>
$(document).ready(function() {
    $('#credito_list').DataTable();
    $('#credito_a_list').DataTable();
    $('#credito_b_list').DataTable();
} );
</script>
@endpush