app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
    Route::resource('cooperativas', 'CooperativaController');
    Route::resource('solicitudes', 'SolicitudController');
    Route::resource('tipoprestamo', 'TipoPrestamoController');
    Route::resource('credito', 'CreditoController');
    Route::resource('mineral', 'TipoMineralController');
    Route::resource('desembolso', 'DesembolsoController');
    Route::resource('amortizacion', 'AmortizacionController');
    Route::resource('reporte', 'ReporteController');
    Route::post('aprobarsolicitud', 'SolicitudController@aprobarsolicitud');
    Route::get('/test', 'CreditoController@testPlanCredito');
    // Plan de creditos
    Route::get('/plan', 'CreditoController@editPlanCredito');
    Route::post('/plan', 'CreditoController@updatePlanCredito');
    Route::get('/test2', 'CreditoController@testPlanCredito2');
});

Route::get('API/{solicitud}', function (App\Solicitud $solicitud){
    return $solicitud;
})->middleware('throttle:3');

app/Solicitud.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Solicitud extends Model
{
    //
    protected $table = 'solicitudes';

    protected $fillable = array('cooperativa_id', 'tipo_credito_id', 'nro_solicitud', 'nombre_proyecto', 'fecha_solicitud',
        'importe_solicitado','importe_propio', 'importe_total','estado','nombre_proyectista','objeto_prestamo','licencia_ambiental','federacion_afiliacion');
}

app/Http/Controllers/SolicitudController.php
<?php

namespace App\Http\Controllers;

use App\Solicitud;
use App\Cooperativa;
use App\TipoPrestamo;
use App\ResolucionSolicitud;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Http\Request;

use App\Http\Requests;

class SolicitudController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cooperativas = Cooperativa::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        $tipo_prestamos = TipoPrestamo::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        $solicitudes = Solicitud::orderBy('created_at', 'asc')->get();

        return view('solicitud.list', [
            'solicitudes' => $solicitudes,
            'tipo_prestamos' => $tipo_prestamos,
            'cooperativas' => $cooperativas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $cooperativas = Cooperativa::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        $tipo_prestamos = TipoPrestamo::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');

        return view('solicitud.create',['cooperativas' => $cooperativas, 'tipo_prestamos' => $tipo_prestamos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            'nro_solicitud' => 'required|max:255',
//            'nro_registro' => 'unique:solicitudes|required',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withInput()
                ->withErrors($validator);
        }

        $value = new Solicitud();
        $input = $request->all();
        $value->fill($input);
        $value->estado = 0; //estado 0 = pendiente
        $value->importe_total = $value->importe_propio + $value->importe_solicitado; //estado 0 = pendiente

        $value->save();
        return redirect('/solicitudes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $solicitud = Solicitud::findOrFail($id);
        $tipo_prestamo = TipoPrestamo::findOrFail($solicitud->tipo_credito_id);
        $cooperativa = Cooperativa::findOrFail($solicitud->cooperativa_id);

        $saldo_capital=$solicitud->importe_solicitado;
        $plazo=$tipo_prestamo->tiempo_maximo_pago;
        $gracia=$tipo_prestamo->tiempo_de_gracia;
        $interes_anual=$tipo_prestamo->interes;
        $fecha_ini=$solicitud->fecha_solicitud;

        $detalle_plan = $this->createPlanCredito($saldo_capital,$plazo,$gracia,$interes_anual,$fecha_ini);

        return view('solicitud.show',
            ['cooperativa' => $cooperativa,
                'tipo_prestamo' => $tipo_prestamo,
                'detalle_plan' => $detalle_plan])->withSolicitud($solicitud);
//        return view('solicitud.show',['cooperativas' => $cooperativas, 'tipo_prestamos' => $tipo_prestamos])->withSolicitud($solicitud);
    }


    /**
     * Crea un array con el plan de creditos tentativo
     *
     * @param  double $saldo_capital
     * @param  int $plazo
     * @param  int $gracia
     * @param  int $interes_anual
     * @param  Date $fecha_ini
     * @return array
     */
    public function createPlanCredito ($saldo_capital, $plazo, $gracia, $interes_anual,$fecha_ini){

        $interes_mensual=$interes_anual/12/100;

        $cuota_capital_mes=round($saldo_capital/($plazo-$gracia),2); // review division by zero

        $contador_mes =0;
        $date = date('d-m-Y', strtotime($fecha_ini));
        $detalle_plan=[];
        while ($contador_mes < $plazo)
        {
            $detalle_plan[$contador_mes]['fecha']=$date;

            $date=date('d-m-Y', strtotime($date. ' + 30 days'));

            if($contador_mes<$gracia)
            {
                $detalle_plan[$contador_mes]['periodo_gracia']=0;
                $detalle_plan[$contador_mes]['cuota_mes']=0;
                $cuota_interes=round($saldo_capital*$interes_mensual,2);
                $detalle_plan[$contador_mes]['cuota_interes']=$cuota_interes;
                $cuota_total=0+$cuota_interes;
                $detalle_plan[$contador_mes]['cuota_total']=$cuota_total;
                $detalle_plan[$contador_mes]['saldo_capital']=$saldo_capital;
            }
            else
            {
                $detalle_plan[$contador_mes]['periodo_gracia']=1;
                $detalle_plan[$contador_mes]['cuota_mes']=$cuota_capital_mes;
                $cuota_interes=round($saldo_capital*$interes_mensual,2);
                $detalle_plan[$contador_mes]['cuota_interes']=$cuota_interes;
                $cuota_total=$cuota_capital_mes+$cuota_interes;
                $detalle_plan[$contador_mes]['cuota_total']=$cuota_total;
                $saldo_capital=$saldo_capital-$cuota_capital_mes;
                if($saldo_capital>=0){
                    $detalle_plan[$contador_mes]['saldo_capital']=$saldo_capital;
                }
                else{
                    $detalle_plan[$contador_mes]['saldo_capital']=0;
                }

            }
            $contador_mes=$contador_mes + 1;

        }
        return $detalle_plan;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $solicitud = Solicitud::findOrFail($id);
        $cooperativas = Cooperativa::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        $tipo_prestamos = TipoPrestamo::orderBy('created_at', 'asc')->get()->lists('nombre', 'id');
        return view('solicitud.edit',['cooperativas' => $cooperativas, 'tipo_prestamos' => $tipo_prestamos])->withSolicitud($solicitud);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $solicitud = Solicitud::findOrFail($id);
        $validator = Validator::make($request->all(), [
            'nro_solicitud' => 'required|max:255',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                ->withInput()
                ->withErrors($validator);
        }
        $input = $request->all();
        $solicitud->fill($input);
        $solicitud->importe_total = $solicitud->importe_propio + $solicitud->importe_solicitado; //estado 0 = pendiente
        $solicitud->save();


        return redirect('/solicitudes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function aprobarsolicitud(Request $request)
    {


        return $request;
        //
//        $validator = Validator::make($request->all(), [
//            'nro_solicitud' => 'required|max:255',
////            'nro_registro' => 'unique:solicitudes|required',
//        ]);
//
//        if ($validator->fails()) {
//            return Redirect::back()
//                ->withInput()
//                ->withErrors($validator);
//        }
//
//        $value = new Solicitud();
//        $input = $request->all();
//        $value->fill($input);
//        $value->estado = 0; //estado 0 = pendiente
//        $value->importe_total = $value->importe_propio + $value->importe_solicitado; //estado 0 = pendiente
//
//        $value->save();
//        return redirect('/solicitudes');
    }

}

resources/views/solicitud/create.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Solicitud
@endsection
@section('htmlheader_title')
	Crear
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Nueva Solicitud</h3>
              <div class="box-tools pull-right">
                            <a href="{{url('solicitudes')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-th-large'></i> Lista</a>

                            </div>
            </div><!-- /.box-header -->
            <div class="box-body">
<!-- New Task Form -->
        @include('layouts.partials.errors')
                {!! Form::open(array('url' => 'solicitudes')) !!}
                {!! csrf_field() !!}

            <!-- Nombre -->
                <div class="form-group">
                    {!! Form::label('cooperativa_id', 'Cooperativa:', ['class' => 'control-label']) !!}

                    {!! Form::select('cooperativa_id', $cooperativas, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('tipo_credito_id', 'Tipo Creditos:', ['class' => 'control-label']) !!}
                    {!! Form::select('tipo_credito_id', $tipo_prestamos, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('objeto_prestamo', 'Objeto del Prestamo:', ['class' => 'control-label']) !!}
                    {!! Form::select('objeto_prestamo', ['Mineria','Instalacion de planta metalurgica'], ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('nro_solicitud', 'Nro. Solicitud:', ['class' => 'control-label']) !!}
                    {!! Form::text('nro_solicitud', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('nombre_proyecto', 'DENOMINACIÓN DEL PROYECTO:', ['class' => 'control-label']) !!}
                    {!! Form::text('nombre_proyecto', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('nombre_proyectista', 'NOMBRE PROYECTISTA:', ['class' => 'control-label']) !!}
                    {!! Form::text('nombre_proyectista', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('licencia_ambiental', 'LICENCIA AMBIENTAL:', ['class' => 'control-label']) !!}
                    {!! Form::text('licencia_ambiental', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('federacion_afiliacion', 'FEDERACION AFILIADA:', ['class' => 'control-label']) !!}
                    {!! Form::text('federacion_afiliacion', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                            {!! Form::label('fecha_solicitud', 'Fecha Solicitud:', ['class' => 'control-label']) !!}
                            {!! Form::input('date', 'fecha_solicitud', date('d-m-Y'), ['class' => 'form-control']) !!}
                        </div>
                <div class="form-group">
                    {!! Form::label('importe_solicitado', 'Importe Solicitado:', ['class' => 'control-label']) !!}
                    {!! Form::text('importe_solicitado', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('importe_propio', 'Importe Propio:', ['class' => 'control-label']) !!}
                    {!! Form::text('importe_propio', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('importe_total', 'Importe Total:', ['class' => 'control-label']) !!}
                    {!! Form::text('importe_total', null, ['class' => 'form-control']) !!}
                </div>
                {{--<div class="form-group">--}}
                    {{--{!! Form::label('adjunto', 'Archivo Adjunto:', ['class' => 'control-label']) !!}--}}
                    {{--{!! Form::file('adjunto', null, ['class' => 'form-control']) !!}--}}
                {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--{!! Form::label('requisitos', 'Requisitos:', ['class' => 'control-label']) !!}--}}
                    {{--{!! Form::text('requisitos', null, ['class' => 'form-control']) !!}--}}
                {{--</div>--}}

                {{--array('cooperativa_id', 'tipo_credito_id', 'nro_solicitud', 'nombre_proyecto', 'fecha_solicitud',--}}
                {{--'importe_solicitado','importe_propio', 'importe_total','estado');--}}
            <!-- Add Button -->
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Añadir nuevo
                    </button>
                </div>
            </div>

        {!! Form::close() !!}

            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
{{--@push('pagescripts')--}}
{{--<script>--}}
{{--$(document).ready(function() {--}}
    {{--$('#example').DataTable();--}}
{{--} );--}}
{{--</script>--}}
{{--@endpush--}}

resources/views/solicitud/edit.blade.php
@extends('layouts.app')

@section('contentheader_title')
    Solicitudes
@endsection
@section('htmlheader_title')
	Editar
@endsection


@section('main-content')
<div class="row">
        <div class="col-xs-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Editar Solicitud</h3>
              <div class="box-tools pull-right">
                            <a href="{{url('solicitudes')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-th-large'></i> Lista</a>

                            </div>
            </div><!-- /.box-header -->
            <div class="box-body">
<!-- New Task Form -->
        @include('layouts.partials.errors')
        {!! Form::model($solicitud, array('route' => array('solicitudes.update', $solicitud->id), 'method' => 'put')) !!}


        <!-- Nombre -->
                        <div class="form-group">
                            {!! Form::label('cooperativa_id', 'Cooperativa:', ['class' => 'control-label']) !!}

                            {!! Form::select('cooperativa_id', $cooperativas) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('tipo_credito_id', 'Tipo Creditos:', ['class' => 'control-label']) !!}
                            {!! Form::select('tipo_credito_id', $tipo_prestamos) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('nro_solicitud', 'Nro. Solicitud:', ['class' => 'control-label']) !!}
                            {!! Form::text('nro_solicitud', null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('nombre_proyecto', 'DENOMINACIÓN DEL PROYECTO:', ['class' => 'control-label']) !!}
                            {!! Form::text('nombre_proyecto', null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                                    {!! Form::label('fecha_solicitud', 'Fecha Solicitud:', ['class' => 'control-label']) !!}
                                    {!! Form::input('date', 'fecha_solicitud', date('d-m-Y'), ['class' => 'form-control']) !!}
                                </div>
                        <div class="form-group">
                            {!! Form::label('importe_solicitado', 'Importe Solicitado:', ['class' => 'control-label']) !!}
                            {!! Form::text('importe_solicitado', null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('importe_propio', 'Importe Propio:', ['class' => 'control-label']) !!}
                            {!! Form::text('importe_propio', null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('importe_total', 'Importe Total:', ['class' => 'control-label']) !!}
                            {!! Form::text('importe_total', null, ['class' => 'form-control']) !!}
                        </div>
                        {{--<div class="form-group">--}}
                            {{--{!! Form::label('adjunto', 'Archivo Adjunto:', ['class' => 'control-label']) !!}--}}
                            {{--{!! Form::file('adjunto', null, ['class' => 'form-control']) !!}--}}
                        {{--</div>--}}
                        {{--<div class="form-group">--}}
                            {{--{!! Form::label('requisitos', 'Requisitos:', ['class' => 'control-label']) !!}--}}
                            {{--{!! Form::text('requisitos', null, ['class' => 'form-control']) !!}--}}
                        {{--</div>--}}

                        {{--array('cooperativa_id', 'tipo_credito_id', 'nro_solicitud', 'nombre_proyecto', 'fecha_solicitud',--}}
                        {{--'importe_solicitado','importe_propio', 'importe_total','estado');--}}
                    <!-- Add Button -->
                    {!! Form::submit('Actualizar registro', ['class' => 'btn btn-primary']) !!}

                {!! Form::close() !!}

            </div><!-- /.box-body -->
          </div><!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
{{--@push('pagescripts')--}}
{{--<script>--}}
{{--$(document).ready(function() {--}}
    {{--$('#example').DataTable();--}}
{{--} );--}}
{{--</script>--}}
{{--@endpush--}}

resources/views/solicitud/list.blade.php
@extends('layouts.app')

@section('contentheader_title')
	Solicitud
@endsection
@section('htmlheader_title')
	Lista
@endsection


@section('main-content')
<div class="row">
<div class="col-xs-12">
<div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Todas las solicitudes</a></li>
              <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">Pendientes</a></li>
              <li><a href="#tab_3" data-toggle="tab">Aprobadas</a></li>
              <li class="box-tools pull-right"><a href="{{url('solicitudes/create')}}" class="btn btn-sm btn-info btn-flat pull-left"><i class='fa fa-plus'></i> Nueva</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                <div class="box-body">
                                <table id="solicitud_list" class="display" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>Acciones</th>
                                                <th>Cooperativa</th>
                                                <th>Tipo Credito</th>
                                                <th>Nro. Solicitud</th>
                                                <th>Proyecto</th>
                                                <th>Fecha Solicitud</th>
                                                <th>Importe</th>
                                                <th>Estado</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                        @foreach ($solicitudes as $solicitud)
                                            <tr>
                                                <td>
                                                <div class="btn-group">
                                                <a href="{{route('solicitudes.show', $solicitud->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                                                <a href="{{route('solicitudes.edit', $solicitud->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                                                </div>

                                                </td>
                                                <td>{{ $cooperativas[$solicitud->cooperativa_id] }}</td>
                                                <td>{{ $tipo_prestamos[$solicitud->tipo_credito_id] }}</td>
                                                <td>{{ $solicitud->nro_solicitud }}</td>
                                                <td>{{ $solicitud->nombre_proyecto }}</td>
                                                <td>{{ $solicitud->fecha_solicitud }}</td>
                                                <td>{{ $solicitud->importe_solicitado }}</td>
                                                <td>{{ $solicitud->estado==0? "Pendiente":"Aprobado"  }}</td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>

                                            </div>
              </div>
              <!-- /.tab-pane -->
              <div class="tab-pane" id="tab_2">
                <div class="box-body">
                                <table id="solicitud_b_list" class="display" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>Acciones</th>
                                        <th>Cooperativa</th>
                                        <th>Tipo Credito</th>
                                        <th>Nro. Solicitud</th>
                                        <th>Proyecto</th>
                                        <th>Fecha Solicitud</th>
                                        <th>Importe</th>
                                        <th>Estado</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @foreach ($solicitudes as $solicitud)
                                        @if($solicitud->estado == 0)
                                        <tr>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{route('solicitudes.show', $solicitud->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                                                    <a href="{{route('solicitudes.edit', $solicitud->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                                                </div>

                                            </td>
                                            <td>{{ $cooperativas[$solicitud->cooperativa_id] }}</td>
                                            <td>{{ $tipo_prestamos[$solicitud->tipo_credito_id] }}</td>
                                            <td>{{ $solicitud->nro_solicitud }}</td>
                                            <td>{{ $solicitud->nombre_proyecto }}</td>
                                            <td>{{ $solicitud->fecha_solicitud }}</td>
                                            <td>{{ $solicitud->importe_solicitado }}</td>
                                            <td>{{ $solicitud->estado==0? "Pendiente":"Aprobado"  }}</td>
                                        </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>
              </div>
              <!-- /.tab-pane -->
              <div class="tab-pane" id="tab_3">
                <div class="box-body">
                                <table id="solicitud_a_list" class="display" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>Acciones</th>
                                        <th>Cooperativa</th>
                                        <th>Tipo Credito</th>
                                        <th>Nro. Solicitud</th>
                                        <th>Proyecto</th>
                                        <th>Fecha Solicitud</th>
                                        <th>Importe</th>
                                        <th>Estado</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @foreach ($solicitudes as $solicitud)
                                        @if($solicitud->estado == 1)
                                        <tr>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{route('solicitudes.show', $solicitud->id)}}" class="btn btn-primary btn-xs"><i class='fa fa-eye'></i> </a>
                                                    <a href="{{route('solicitudes.edit', $solicitud->id)}}" class="btn btn-info btn-xs"><i class='fa fa-edit'></i> </a>
                                                </div>

                                            </td>
                                            <td>{{ $cooperativas[$solicitud->cooperativa_id] }}</td>
                                            <td>{{ $tipo_prestamos[$solicitud->tipo_credito_id] }}</td>
                                            <td>{{ $solicitud->nro_solicitud }}</td>
                                            <td>{{ $solicitud->nombre_proyecto }}</td>
                                            <td>{{ $solicitud->fecha_solicitud }}</td>
                                            <td>{{ $solicitud->importe_solicitado }}</td>
                                            <td>{{ $solicitud->estado==0? "Pendiente":"Aprobado"  }}</td>
                                        </tr>
                                        @endif
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>
              </div>
              <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
          </div>
</div>
        <div class="col-xs-12">
          <!-- /.box -->

        </div>
        <!-- /.col -->
      </div>

@endsection
@push('pagescripts')
<script>
$(document).ready(function() {
    $('#solicitud_list').DataTable();
    $('#solicitud_a_list').DataTable();
    $('#solicitud_b_list').DataTable();
} );
</script>
@endpush